# Project 01 — Churn Prediction

Predicting bank customer churn using multiple approaches:
baseline classifiers, Random Forest, Scikit-learn MLP, Keras, TensorFlow, and a custom NumPy neural network.

In [1]:
%pip install tensorflow scikit-learn numpy pandas --quiet

Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os
os.makedirs("../models", exist_ok=True)

In [ ]:
import sys, os
sys.path.insert(0, '../src')
sys.path.insert(0, '..')  # for my_neural_net.py
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=0"

from features import get_train_test_data
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    tf.config.experimental.set_memory_growth(gpus[0], True)

data = get_train_test_data(
    "../data/bank_data_train.csv",
    num_impute="mean",
)

print(f"x_train: {data.x_train.shape}")
print(f"x_test:  {data.x_test.shape}")
data.x_train.head()

x_train: (284152, 113)
x_test:  (71038, 113)

,CR_PROD_CNT_IL,AMOUNT_RUB_CLO_PRC,PRC_ACCEPTS_A_EMAIL_LINK,APP_REGISTR_RGN_CODE,PRC_ACCEPTS_A_POS,PRC_ACCEPTS_A_TK,TURNOVER_DYNAMIC_IL_1M,CNT_TRAN_AUT_TENDENCY1M,SUM_TRAN_AUT_TENDENCY1M,AMOUNT_RUB_SUP_PRC,...,PACK_103,PACK_104,PACK_105,PACK_107,PACK_108,PACK_109,PACK_301,PACK_K01,PACK_M01,PACK_O01
54105,2.720640,0.023391,0.0,0.302862,0.0,0.0,-0.047265,-1.067741,-1.651879,1.976389,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
313302,-0.274469,-0.479320,0.0,0.091351,0.0,0.0,-0.047265,0.050608,0.054461,-0.556620,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
302648,-0.274469,-0.479320,0.0,0.091351,0.0,0.0,-0.047265,0.050608,0.054461,-0.708387,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
350887,2.720640,0.336979,0.0,0.302862,0.0,0.0,-0.047265,0.050608,0.054461,0.505013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41493,-0.274469,-0.423432,0.0,0.302862,0.0,0.0,-0.047265,3.576069,3.315444,0.771324,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
print(f"Features used for training: {data.x_train.columns.tolist()}")

Features used for training: ['CR_PROD_CNT_IL', 'AMOUNT_RUB_CLO_PRC', 'PRC_ACCEPTS_A_EMAIL_LINK', 'APP_REGISTR_RGN_CODE', 'PRC_ACCEPTS_A_POS', 'PRC_ACCEPTS_A_TK', 'TURNOVER_DYNAMIC_IL_1M', 'CNT_TRAN_AUT_TENDENCY1M', 'SUM_TRAN_AUT_TENDENCY1M', 'AMOUNT_RUB_SUP_PRC', 'PRC_ACCEPTS_A_AMOBILE', 'SUM_TRAN_AUT_TENDENCY3M', 'PRC_ACCEPTS_TK', 'PRC_ACCEPTS_A_MTP', 'REST_DYNAMIC_FDEP_1M', 'CNT_TRAN_AUT_TENDENCY3M', 'CNT_ACCEPTS_TK', 'REST_DYNAMIC_SAVE_3M', 'CR_PROD_CNT_VCU', 'REST_AVG_CUR', 'CNT_TRAN_MED_TENDENCY1M', 'AMOUNT_RUB_NAS_PRC', 'TRANS_COUNT_SUP_PRC', 'CNT_TRAN_CLO_TENDENCY1M', 'SUM_TRAN_MED_TENDENCY1M', 'PRC_ACCEPTS_A_ATM', 'PRC_ACCEPTS_MTP', 'TRANS_COUNT_NAS_PRC', 'CNT_ACCEPTS_MTP', 'CR_PROD_CNT_TOVR', 'CR_PROD_CNT_PIL', 'SUM_TRAN_CLO_TENDENCY1M', 'TURNOVER_CC', 'TRANS_COUNT_ATM_PRC', 'AMOUNT_RUB_ATM_PRC', 'TURNOVER_PAYM', 'AGE', 'CNT_TRAN_MED_TENDENCY3M', 'CR_PROD_CNT_CC', 'SUM_TRAN_MED_TENDENCY3M', 'REST_DYNAMIC_FDEP_3M', 'REST_DYNAMIC_IL_1M', 'SUM_TRAN_CLO_TENDENCY3M', 'LDEAL_TENOR_MAX', 'LDEAL_YQZ_CHRG', 'CR_PROD_CNT_CCFP', 'DEAL_YQZ_IR_MAX', 'LDEAL_YQZ_COM', 'DEAL_YQZ_IR_MIN', 'CNT_TRAN_CLO_TENDENCY3M', 'REST_DYNAMIC_CUR_1M', 'REST_AVG_PAYM', 'LDEAL_TENOR_MIN', 'LDEAL_AMT_MONTH', 'LDEAL_GRACE_DAYS_PCT_MED', 'REST_DYNAMIC_CUR_3M', 'CNT_TRAN_SUP_TENDENCY3M', 'TURNOVER_DYNAMIC_CUR_1M', 'REST_DYNAMIC_PAYM_3M', 'SUM_TRAN_SUP_TENDENCY3M', 'REST_DYNAMIC_IL_3M', 'CNT_TRAN_ATM_TENDENCY3M', 'CNT_TRAN_ATM_TENDENCY1M', 'TURNOVER_DYNAMIC_IL_3M', 'SUM_TRAN_ATM_TENDENCY3M', 'DEAL_GRACE_DAYS_ACC_S1X1', 'AVG_PCT_MONTH_TO_PCLOSE', 'DEAL_YWZ_IR_MIN', 'SUM_TRAN_SUP_TENDENCY1M', 'DEAL_YWZ_IR_MAX', 'SUM_TRAN_ATM_TENDENCY1M', 'REST_DYNAMIC_PAYM_1M', 'CNT_TRAN_SUP_TENDENCY1M', 'DEAL_GRACE_DAYS_ACC_AVG', 'TURNOVER_DYNAMIC_CUR_3M', 'MAX_PCLOSE_DATE', 'LDEAL_YQZ_PC', 'CLNT_SETUP_TENOR', 'DEAL_GRACE_DAYS_ACC_MAX', 'TURNOVER_DYNAMIC_PAYM_3M', 'LDEAL_DELINQ_PER_MAXYQZ', 'TURNOVER_DYNAMIC_PAYM_1M', 'CLNT_SALARY_VALUE', 'TRANS_AMOUNT_TENDENCY3M', 'MED_DEBT_PRC_YQZ', 'TRANS_CNT_TENDENCY3M', 'LDEAL_USED_AMT_AVG_YQZ', 'REST_DYNAMIC_CC_1M', 'LDEAL_USED_AMT_AVG_YWZ', 'TURNOVER_DYNAMIC_CC_1M', 'AVG_PCT_DEBT_TO_DEAL_AMT', 'LDEAL_ACT_DAYS_ACC_PCT_AVG', 'REST_DYNAMIC_CC_3M', 'MED_DEBT_PRC_YWZ', 'LDEAL_ACT_DAYS_PCT_TR3', 'LDEAL_ACT_DAYS_PCT_AAVG', 'LDEAL_DELINQ_PER_MAXYWZ', 'TURNOVER_DYNAMIC_CC_3M', 'LDEAL_ACT_DAYS_PCT_TR', 'LDEAL_ACT_DAYS_PCT_TR4', 'LDEAL_ACT_DAYS_PCT_CURR', 'PACK_101', 'PACK_102', 'PACK_103', 'PACK_104', 'PACK_105', 'PACK_107', 'PACK_108', 'PACK_109', 'PACK_301', 'PACK_K01', 'PACK_M01', 'PACK_O01']

## Class Imbalance Handling

The dataset is heavily imbalanced (~91 % non-churn / ~9 % churn).
Balanced class weights are computed here and passed to all neural-network `fit()` calls so that the minority class receives proportionally higher loss weighting — no resampling required.

In [4]:
print("Class distribution (train):")
print(data.y_train.value_counts().to_string())
print(f"\nBalanced class weights: {data.class_weight}")

Class distribution (train):
TARGET
0    261012
1     23140

Balanced class weights: {0: 0.5443274638713929, 1: 6.139844425237683}

## 1. Baseline Solutions

### 1.1 Naive Classifier

Always predicts the most frequent class.

In [5]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import roc_auc_score, accuracy_score, classification_report

naive_clf = DummyClassifier(strategy='most_frequent')
naive_clf.fit(data.x_train, data.y_train)

naive_y_pred  = naive_clf.predict(data.x_test)
naive_y_proba = naive_clf.predict_proba(data.x_test)[:, 1]

naive_acc = accuracy_score(data.y_test, naive_y_pred)
naive_auc = roc_auc_score(data.y_test, naive_y_proba)

print(f"Accuracy: {naive_acc:.4f}")
print(f"AUC:      {naive_auc:.4f}")
print()
print(classification_report(data.y_test, naive_y_pred))

Accuracy: 0.9186
AUC:      0.5000

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     65253
           1       0.00      0.00      0.00      5785

    accuracy                           0.92     71038
   macro avg       0.46      0.50      0.48     71038
weighted avg       0.84      0.92      0.88     71038

/goinfre/stamim/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/goinfre/stamim/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/goinfre/stamim/churn/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### 1.2 Random Forest with Grid Search

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.model_selection import GridSearchCV

rf_param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt'],
}

rf_grid = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid=rf_param_grid,
    scoring='roc_auc',
    cv=3,
    verbose=1,
    n_jobs=-1,
)
rf_grid.fit(data.x_train, data.y_train)

rf_best_params = rf_grid.best_params_
rf_auc = roc_auc_score(data.y_test, rf_grid.predict_proba(data.x_test)[:, 1])
rf_acc = accuracy_score(data.y_test, rf_grid.predict(data.x_test))

print(f"Best params: {rf_best_params}")
print(f"AUC:         {rf_auc:.4f}")
print(f"Accuracy:    {rf_acc:.4f}")

Fitting 3 folds for each of 36 candidates, totalling 108 fits
Best params: {'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 200}
AUC:         0.8353
Accuracy:    0.9194

## 2. Neural Networks

### 2.1 NumPy Neural Network

Custom fully-connected neural network implemented from scratch using NumPy (OOP, matrix calculations).

In [7]:
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath("__file__")), '..', 'src'))

from my_neural_net import MyNeuralNet

NUMPY_HIDDEN = [512, 256, 128]
NUMPY_EPOCHS = 60
NUMPY_LR     = 0.001
NUMPY_BATCH  = 256

numpy_model = MyNeuralNet(
    hidden_layers_size=NUMPY_HIDDEN,
    max_iter=NUMPY_EPOCHS,
    learning_rate=NUMPY_LR,
    batch_size=NUMPY_BATCH,
)
numpy_model.fit(
    data.x_train,
    data.y_train,
    class_weight=data.class_weight,
    validation_data=(data.x_test, data.y_test),
)

numpy_auc = numpy_model.auc_score(data.x_test, data.y_test)
numpy_acc = numpy_model.score(data.x_test, data.y_test)

print(f"AUC:      {numpy_auc:.4f}")
print(f"Accuracy: {numpy_acc:.4f}")

Epoch 1/60, Loss: 0.6840 - Acc: 0.5991 - AUC: 0.6628 - Val Acc: 0.5977 - Val AUC: 0.6605
Epoch 2/60, Loss: 0.6452 - Acc: 0.6222 - AUC: 0.6978 - Val Acc: 0.6205 - Val AUC: 0.6921
Epoch 3/60, Loss: 0.6286 - Acc: 0.6642 - AUC: 0.7171 - Val Acc: 0.6607 - Val AUC: 0.7096
Epoch 4/60, Loss: 0.6164 - Acc: 0.6555 - AUC: 0.7318 - Val Acc: 0.6529 - Val AUC: 0.7230
Epoch 5/60, Loss: 0.6066 - Acc: 0.6803 - AUC: 0.7419 - Val Acc: 0.6767 - Val AUC: 0.7323
Epoch 6/60, Loss: 0.5982 - Acc: 0.6599 - AUC: 0.7513 - Val Acc: 0.6557 - Val AUC: 0.7407
Epoch 7/60, Loss: 0.5909 - Acc: 0.6776 - AUC: 0.7585 - Val Acc: 0.6730 - Val AUC: 0.7471
Epoch 8/60, Loss: 0.5846 - Acc: 0.6870 - AUC: 0.7644 - Val Acc: 0.6836 - Val AUC: 0.7526
Epoch 9/60, Loss: 0.5790 - Acc: 0.6880 - AUC: 0.7697 - Val Acc: 0.6843 - Val AUC: 0.7573
Epoch 10/60, Loss: 0.5738 - Acc: 0.6851 - AUC: 0.7743 - Val Acc: 0.6809 - Val AUC: 0.7612
Epoch 11/60, Loss: 0.5696 - Acc: 0.6901 - AUC: 0.7785 - Val Acc: 0.6858 - Val AUC: 0.7650
Epoch 12/60, Loss: 0.5653 - Acc: 0.6740 - AUC: 0.7820 - Val Acc: 0.6703 - Val AUC: 0.7681
Epoch 13/60, Loss: 0.5616 - Acc: 0.6874 - AUC: 0.7853 - Val Acc: 0.6838 - Val AUC: 0.7711
Epoch 14/60, Loss: 0.5580 - Acc: 0.6833 - AUC: 0.7881 - Val Acc: 0.6798 - Val AUC: 0.7734
Epoch 15/60, Loss: 0.5551 - Acc: 0.6803 - AUC: 0.7905 - Val Acc: 0.6763 - Val AUC: 0.7753
Epoch 16/60, Loss: 0.5521 - Acc: 0.6969 - AUC: 0.7929 - Val Acc: 0.6924 - Val AUC: 0.7775
Epoch 17/60, Loss: 0.5493 - Acc: 0.6892 - AUC: 0.7952 - Val Acc: 0.6849 - Val AUC: 0.7793
Epoch 18/60, Loss: 0.5469 - Acc: 0.6870 - AUC: 0.7973 - Val Acc: 0.6826 - Val AUC: 0.7810
Epoch 19/60, Loss: 0.5443 - Acc: 0.7117 - AUC: 0.7988 - Val Acc: 0.7072 - Val AUC: 0.7823
Epoch 20/60, Loss: 0.5425 - Acc: 0.7065 - AUC: 0.8008 - Val Acc: 0.7020 - Val AUC: 0.7839
Epoch 21/60, Loss: 0.5404 - Acc: 0.7042 - AUC: 0.8024 - Val Acc: 0.6996 - Val AUC: 0.7850
Epoch 22/60, Loss: 0.5383 - Acc: 0.7069 - AUC: 0.8040 - Val Acc: 0.7017 - Val AUC: 0.7863
Epoch 23/60, Loss: 0.5366 - Acc: 0.7086 - AUC: 0.8055 - Val Acc: 0.7031 - Val AUC: 0.7875
Epoch 24/60, Loss: 0.5352 - Acc: 0.7157 - AUC: 0.8066 - Val Acc: 0.7105 - Val AUC: 0.7882
Epoch 25/60, Loss: 0.5331 - Acc: 0.7206 - AUC: 0.8080 - Val Acc: 0.7153 - Val AUC: 0.7894
Epoch 26/60, Loss: 0.5318 - Acc: 0.7093 - AUC: 0.8095 - Val Acc: 0.7036 - Val AUC: 0.7905
Epoch 27/60, Loss: 0.5301 - Acc: 0.7030 - AUC: 0.8106 - Val Acc: 0.6973 - Val AUC: 0.7912
Epoch 28/60, Loss: 0.5284 - Acc: 0.7079 - AUC: 0.8115 - Val Acc: 0.7025 - Val AUC: 0.7921
Epoch 29/60, Loss: 0.5270 - Acc: 0.7223 - AUC: 0.8125 - Val Acc: 0.7167 - Val AUC: 0.7927
Epoch 30/60, Loss: 0.5255 - Acc: 0.7218 - AUC: 0.8137 - Val Acc: 0.7161 - Val AUC: 0.7936
Epoch 31/60, Loss: 0.5244 - Acc: 0.7235 - AUC: 0.8146 - Val Acc: 0.7176 - Val AUC: 0.7943
Epoch 32/60, Loss: 0.5234 - Acc: 0.6980 - AUC: 0.8158 - Val Acc: 0.6921 - Val AUC: 0.7947
Epoch 33/60, Loss: 0.5221 - Acc: 0.7075 - AUC: 0.8168 - Val Acc: 0.7021 - Val AUC: 0.7955
Epoch 34/60, Loss: 0.5206 - Acc: 0.6949 - AUC: 0.8177 - Val Acc: 0.6887 - Val AUC: 0.7961
Epoch 35/60, Loss: 0.5197 - Acc: 0.7113 - AUC: 0.8186 - Val Acc: 0.7060 - Val AUC: 0.7969
Epoch 36/60, Loss: 0.5186 - Acc: 0.7139 - AUC: 0.8193 - Val Acc: 0.7080 - Val AUC: 0.7970
Epoch 37/60, Loss: 0.5174 - Acc: 0.7292 - AUC: 0.8198 - Val Acc: 0.7239 - Val AUC: 0.7973
Epoch 38/60, Loss: 0.5165 - Acc: 0.7140 - AUC: 0.8210 - Val Acc: 0.7085 - Val AUC: 0.7982
Epoch 39/60, Loss: 0.5156 - Acc: 0.7228 - AUC: 0.8217 - Val Acc: 0.7174 - Val AUC: 0.7990
Epoch 40/60, Loss: 0.5141 - Acc: 0.7235 - AUC: 0.8225 - Val Acc: 0.7182 - Val AUC: 0.7993
Epoch 41/60, Loss: 0.5132 - Acc: 0.7101 - AUC: 0.8231 - Val Acc: 0.7038 - Val AUC: 0.7998
Epoch 42/60, Loss: 0.5124 - Acc: 0.7192 - AUC: 0.8240 - Val Acc: 0.7126 - Val AUC: 0.7999
Epoch 43/60, Loss: 0.5113 - Acc: 0.7154 - AUC: 0.8247 - Val Acc: 0.7095 - Val AUC: 0.8005
Epoch 44/60, Loss: 0.5105 - Acc: 0.7214 - AUC: 0.8253 - Val Acc: 0.7155 - Val AUC: 0.8007
Epoch 45/60, Loss: 0.5095 - Acc: 0.7214 - AUC: 0.8260 - Val Acc: 0.7156 - Val AUC: 0.8009
Epoch 46/60, Loss: 0.5086 - Acc: 0.7076 - AUC: 0.8267 - Val Acc: 0.7012 - Val AUC: 0.8018
Epoch 47/60, Loss: 0.5079 - Acc: 0.7291 - AUC: 0.8271 - Val Acc: 0.7234 - Val AUC: 0.8016
Epoch 48/60, Loss: 0.5069 - Acc: 0.7109 - AUC: 0.8280 - Val Acc: 0.7041 - Val AUC: 0.8022
Epoch 49/60, Loss: 0.5064 - Acc: 0.7126 - AUC: 0.8286 - Val Acc: 0.7061 - Val AUC: 0.8029
Epoch 50/60, Loss: 0.5054 - Acc: 0.7199 - AUC: 0.8293 - Val Acc: 0.7137 - Val AUC: 0.8030
Epoch 51/60, Loss: 0.5045 - Acc: 0.7065 - AUC: 0.8296 - Val Acc: 0.6995 - Val AUC: 0.8033
Epoch 52/60, Loss: 0.5035 - Acc: 0.7235 - AUC: 0.8304 - Val Acc: 0.7169 - Val AUC: 0.8036
Epoch 53/60, Loss: 0.5030 - Acc: 0.7290 - AUC: 0.8309 - Val Acc: 0.7222 - Val AUC: 0.8034
Epoch 54/60, Loss: 0.5020 - Acc: 0.7180 - AUC: 0.8317 - Val Acc: 0.7115 - Val AUC: 0.8043
Epoch 55/60, Loss: 0.5013 - Acc: 0.7149 - AUC: 0.8323 - Val Acc: 0.7082 - Val AUC: 0.8043
Epoch 56/60, Loss: 0.5006 - Acc: 0.7257 - AUC: 0.8327 - Val Acc: 0.7189 - Val AUC: 0.8042
Epoch 57/60, Loss: 0.4995 - Acc: 0.7248 - AUC: 0.8332 - Val Acc: 0.7178 - Val AUC: 0.8044
Epoch 58/60, Loss: 0.4990 - Acc: 0.7405 - AUC: 0.8335 - Val Acc: 0.7331 - Val AUC: 0.8048
Epoch 59/60, Loss: 0.4984 - Acc: 0.7327 - AUC: 0.8339 - Val Acc: 0.7256 - Val AUC: 0.8049
Epoch 60/60, Loss: 0.4975 - Acc: 0.7117 - AUC: 0.8349 - Val Acc: 0.7045 - Val AUC: 0.8056
AUC:      0.8056
Accuracy: 0.7045

### 2.2 Scikit-learn MLPClassifier

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score, accuracy_score

MLP_HIDDEN   = (512, 256, 128)
MLP_MAX_ITER = 10
MLP_LR       = 0.001
MLP_BATCH    = 256

mlp_model = MLPClassifier(
    hidden_layer_sizes=MLP_HIDDEN,
    activation="relu",
    solver="adam",
    learning_rate_init=MLP_LR,
    max_iter=MLP_MAX_ITER,
    random_state=42,
    verbose=True,
    batch_size=MLP_BATCH,
)
mlp_model.fit(data.x_train, data.y_train)

mlp_auc = roc_auc_score(data.y_test, mlp_model.predict_proba(data.x_test)[:, 1])
mlp_acc = accuracy_score(data.y_test, mlp_model.predict(data.x_test))

print(f"AUC:      {mlp_auc:.4f}")
print(f"Accuracy: {mlp_acc:.4f}")

Iteration 1, loss = 0.24254425
Iteration 2, loss = 0.22715369
Iteration 3, loss = 0.22265403
Iteration 4, loss = 0.21970038
Iteration 5, loss = 0.21707609
Iteration 6, loss = 0.21521434
Iteration 7, loss = 0.21313747
Iteration 8, loss = 0.21091619
Iteration 9, loss = 0.20881592
Iteration 10, loss = 0.20643262

/goinfre/stamim/churn/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

AUC:      0.8294
Accuracy: 0.9174

### 2.3 Keras (TensorFlow)

Residual fully-connected network built with `tf.keras`, trained with grid search over hyperparameters.

In [10]:
from NN_GridSearch import (
    create_model,
    PARAM_GRID,
    LOSS_FUNCTION,
)
from tensorflow.keras.callbacks import EarlyStopping
from itertools import product
import pandas as pd

KERAS_MODEL_PATH = "../models/best_model_keras.keras"
KERAS_RUN_GRID = False

if KERAS_RUN_GRID:
    keras_keys = list(PARAM_GRID.keys())
    keras_combos = list(product(*PARAM_GRID.values()))
else:
    keras_combos = [(0.001, 0.1, 1e-6, 256, 200, 512)]
    keras_keys = [
        "learning_rate",
        "dropout_rate",
        "l2_reg",
        "batch_size",
        "epochs",
        "hidden_units",
    ]

keras_global_best = {"auc": 0.0}
keras_results = []
keras_params = {}


for run_idx, values in enumerate(keras_combos, 1):
    keras_params = dict(zip(keras_keys, values))
    print(f"\n[{run_idx}/{len(keras_combos)}] {keras_params}")

    tf.keras.backend.clear_session()

    keras_model = create_model(
        data.x_train.shape[1],
        keras_params["hidden_units"],
        dropout_rate=keras_params["dropout_rate"],
        l2_reg=keras_params["l2_reg"],
    )
    keras_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=keras_params["learning_rate"]),
        loss=LOSS_FUNCTION,
        metrics=[tf.keras.metrics.AUC(name="auc"), "accuracy"],
    )

    erl = EarlyStopping(
        monitor="val_auc",
        mode="max",
        patience=3,
        restore_best_weights=True,
    )

    keras_model.fit(
        data.x_train,
        data.y_train,
        epochs=keras_params["epochs"],
        batch_size=keras_params["batch_size"],
        callbacks=[erl],
        validation_data=(data.x_test, data.y_test),
        class_weight=data.class_weight,
        verbose=1,
    )
    _, keras_val_auc, _ = keras_model.evaluate(data.x_test, data.y_test, verbose=0)
    print(f"  ✔ best val_auc: {keras_val_auc:.4f}")
    keras_results.append({**keras_params, "val_auc": keras_val_auc})
    if keras_val_auc > keras_global_best["auc"]:
        keras_global_best["auc"] = keras_val_auc
        keras_model.save(KERAS_MODEL_PATH)

keras_df = (
    pd.DataFrame(keras_results)
    .sort_values("val_auc", ascending=False)
    .reset_index(drop=True)
)
keras_df.index += 1
print(f"\n{'═'*70}\n{keras_df.to_string()}\n{'═'*70}")

keras_best_model = tf.keras.models.load_model(KERAS_MODEL_PATH)
_, keras_auc, keras_acc = keras_best_model.evaluate(data.x_test, data.y_test, verbose=0)
print(f"\nKeras best model  —  test AUC: {keras_auc:.4f}  |  accuracy: {keras_acc:.4f}")

[1/1] {'learning_rate': 0.001, 'dropout_rate': 0.1, 'l2_reg': 1e-06, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.6451 - auc: 0.7795 - loss: 0.5634 - val_accuracy: 0.6560 - val_auc: 0.8058 - val_loss: 0.5623
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6793 - auc: 0.8162 - loss: 0.5224 - val_accuracy: 0.6889 - val_auc: 0.8155 - val_loss: 0.5183
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6839 - auc: 0.8252 - loss: 0.5105 - val_accuracy: 0.6563 - val_auc: 0.8205 - val_loss: 0.5092
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6926 - auc: 0.8314 - loss: 0.5023 - val_accuracy: 0.7280 - val_auc: 0.8271 - val_loss: 0.4981
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7019 - auc: 0.8360 - loss: 0.4962 - val_accuracy: 0.6966 - val_auc: 0.8271 - val_loss: 0.5285
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7003 - auc: 0.8398 - loss: 0.4912 - val_accuracy: 0.7149 - val_auc: 0.8256 - val_loss: 0.4823
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7044 - auc: 0.8442 - loss: 0.4840 - val_accuracy: 0.6950 - val_auc: 0.8301 - val_loss: 0.5316
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7096 - auc: 0.8468 - loss: 0.4805 - val_accuracy: 0.7004 - val_auc: 0.8297 - val_loss: 0.4875
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7156 - auc: 0.8502 - loss: 0.4756 - val_accuracy: 0.6801 - val_auc: 0.8292 - val_loss: 0.5547
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 18s 16ms/step - accuracy: 0.7154 - auc: 0.8540 - loss: 0.4686 - val_accuracy: 0.7076 - val_auc: 0.8316 - val_loss: 0.4893
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7182 - auc: 0.8565 - loss: 0.4653 - val_accuracy: 0.7117 - val_auc: 0.8321 - val_loss: 0.5018
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7180 - auc: 0.8592 - loss: 0.4603 - val_accuracy: 0.7142 - val_auc: 0.8277 - val_loss: 0.4701
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7235 - auc: 0.8625 - loss: 0.4555 - val_accuracy: 0.7141 - val_auc: 0.8273 - val_loss: 0.5028
Epoch 14/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7275 - auc: 0.8662 - loss: 0.4497 - val_accuracy: 0.7533 - val_auc: 0.8286 - val_loss: 0.4577
  ✔ best val_auc: 0.8321

══════════════════════════════════════════════════════════════════════
   learning_rate  dropout_rate    l2_reg  batch_size  epochs  hidden_units   val_auc
1          0.001           0.1  0.000001         256     200           512  0.832086
══════════════════════════════════════════════════════════════════════

Keras best model  —  test AUC: 0.8321  |  accuracy: 0.7117

### 2.4 TensorFlow

Same residual architecture, trained independently with the TensorFlow backend.

In [11]:
TF_MODEL_PATH = "../models/best_model_tf.keras"
TF_RUN_GRID = True

if TF_RUN_GRID:
    tf_keys = list(PARAM_GRID.keys())
    tf_combos = list(product(*PARAM_GRID.values()))
else:
    tf_combos = [(0.001, 0.1, 1e-6, 256, 200, 512)]
    tf_keys = [
        "learning_rate",
        "dropout_rate",
        "l2_reg",
        "batch_size",
        "epochs",
        "hidden_units",
    ]

tf_global_best = {"auc": 0.0}
tf_results = []
tf_params = {}

for run_idx, values in enumerate(tf_combos, 1):
    tf_params = dict(zip(tf_keys, values))
    print(f"\n[{run_idx}/{len(tf_combos)}] {tf_params}")

    tf.keras.backend.clear_session()

    tf_model = create_model(
        data.x_train.shape[1],
        tf_params["hidden_units"],
        dropout_rate=tf_params["dropout_rate"],
        l2_reg=tf_params["l2_reg"],
    )
    tf_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=tf_params["learning_rate"]),
        loss=LOSS_FUNCTION,
        metrics=[tf.keras.metrics.AUC(name="auc"), "accuracy"],
    )

    erl = EarlyStopping(
        monitor="val_auc",
        mode="max",
        patience=3,
        restore_best_weights=True,
    )

    tf_model.fit(
        data.x_train,
        data.y_train,
        epochs=tf_params["epochs"],
        batch_size=tf_params["batch_size"],
        callbacks=[erl],
        validation_data=(data.x_test, data.y_test),
        class_weight=data.class_weight,
        verbose=1,
    )
    _, tf_val_auc, _ = tf_model.evaluate(data.x_test, data.y_test, verbose=0)
    print(f"  ✔ best val_auc: {tf_val_auc:.4f}")
    tf_results.append({**tf_params, "val_auc": tf_val_auc})
    if tf_val_auc > tf_global_best["auc"]:
        tf_global_best["auc"] = tf_val_auc
        tf_model.save(TF_MODEL_PATH)

tf_df = (
    pd.DataFrame(tf_results)
    .sort_values("val_auc", ascending=False)
    .reset_index(drop=True)
)
tf_df.index += 1
print(f"\n{'═'*70}\n{tf_df.to_string()}\n{'═'*70}")

tf_best_model = tf.keras.models.load_model(TF_MODEL_PATH)
_, tf_auc, tf_acc = tf_best_model.evaluate(data.x_test, data.y_test, verbose=0)
print(f"\nTensorFlow best model  —  test AUC: {tf_auc:.4f}  |  accuracy: {tf_acc:.4f}")

[1/8] {'learning_rate': 0.001, 'dropout_rate': 0.1, 'l2_reg': 1e-06, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.6453 - auc: 0.7777 - loss: 0.5664 - val_accuracy: 0.6887 - val_auc: 0.8060 - val_loss: 0.5248
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6799 - auc: 0.8162 - loss: 0.5220 - val_accuracy: 0.7046 - val_auc: 0.8190 - val_loss: 0.4717
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6883 - auc: 0.8251 - loss: 0.5105 - val_accuracy: 0.6597 - val_auc: 0.8235 - val_loss: 0.5614
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6975 - auc: 0.8328 - loss: 0.5006 - val_accuracy: 0.7043 - val_auc: 0.8259 - val_loss: 0.5029
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7034 - auc: 0.8363 - loss: 0.4963 - val_accuracy: 0.6708 - val_auc: 0.8274 - val_loss: 0.5698
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7056 - auc: 0.8397 - loss: 0.4904 - val_accuracy: 0.7013 - val_auc: 0.8306 - val_loss: 0.5259
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7096 - auc: 0.8437 - loss: 0.4852 - val_accuracy: 0.7172 - val_auc: 0.8330 - val_loss: 0.4746
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7124 - auc: 0.8472 - loss: 0.4805 - val_accuracy: 0.6969 - val_auc: 0.8331 - val_loss: 0.5324
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7207 - auc: 0.8508 - loss: 0.4747 - val_accuracy: 0.7244 - val_auc: 0.8311 - val_loss: 0.4898
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7246 - auc: 0.8537 - loss: 0.4705 - val_accuracy: 0.7039 - val_auc: 0.8337 - val_loss: 0.4906
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7237 - auc: 0.8571 - loss: 0.4643 - val_accuracy: 0.7576 - val_auc: 0.8294 - val_loss: 0.4435
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7247 - auc: 0.8590 - loss: 0.4616 - val_accuracy: 0.7304 - val_auc: 0.8327 - val_loss: 0.4613
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7297 - auc: 0.8620 - loss: 0.4575 - val_accuracy: 0.7206 - val_auc: 0.8308 - val_loss: 0.4847
  ✔ best val_auc: 0.8337

[2/8] {'learning_rate': 0.001, 'dropout_rate': 0.1, 'l2_reg': 0.0001, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.6521 - auc: 0.7801 - loss: 0.6842 - val_accuracy: 0.6422 - val_auc: 0.8041 - val_loss: 0.6332
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6799 - auc: 0.8147 - loss: 0.5670 - val_accuracy: 0.6662 - val_auc: 0.8126 - val_loss: 0.5915
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6935 - auc: 0.8242 - loss: 0.5367 - val_accuracy: 0.6732 - val_auc: 0.8218 - val_loss: 0.5617
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6930 - auc: 0.8273 - loss: 0.5264 - val_accuracy: 0.6719 - val_auc: 0.8238 - val_loss: 0.5644
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6964 - auc: 0.8310 - loss: 0.5193 - val_accuracy: 0.6526 - val_auc: 0.8233 - val_loss: 0.6163
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6973 - auc: 0.8332 - loss: 0.5156 - val_accuracy: 0.6456 - val_auc: 0.8270 - val_loss: 0.6178
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7037 - auc: 0.8365 - loss: 0.5108 - val_accuracy: 0.7228 - val_auc: 0.8302 - val_loss: 0.5077
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7048 - auc: 0.8382 - loss: 0.5083 - val_accuracy: 0.7245 - val_auc: 0.8302 - val_loss: 0.4860
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7065 - auc: 0.8397 - loss: 0.5070 - val_accuracy: 0.7136 - val_auc: 0.8300 - val_loss: 0.5070
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7085 - auc: 0.8416 - loss: 0.5038 - val_accuracy: 0.7287 - val_auc: 0.8316 - val_loss: 0.5020
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7084 - auc: 0.8428 - loss: 0.5024 - val_accuracy: 0.6785 - val_auc: 0.8314 - val_loss: 0.5464
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7110 - auc: 0.8447 - loss: 0.5000 - val_accuracy: 0.7231 - val_auc: 0.8326 - val_loss: 0.5117
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7119 - auc: 0.8460 - loss: 0.4982 - val_accuracy: 0.7056 - val_auc: 0.8326 - val_loss: 0.5169
Epoch 14/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7153 - auc: 0.8466 - loss: 0.4987 - val_accuracy: 0.6906 - val_auc: 0.8315 - val_loss: 0.5452
Epoch 15/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7167 - auc: 0.8486 - loss: 0.4952 - val_accuracy: 0.7313 - val_auc: 0.8296 - val_loss: 0.4850
Epoch 16/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7188 - auc: 0.8507 - loss: 0.4928 - val_accuracy: 0.7428 - val_auc: 0.8291 - val_loss: 0.4850
  ✔ best val_auc: 0.8326

[3/8] {'learning_rate': 0.001, 'dropout_rate': 0.3, 'l2_reg': 1e-06, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.6280 - auc: 0.7552 - loss: 0.5892 - val_accuracy: 0.6752 - val_auc: 0.8017 - val_loss: 0.4877
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6643 - auc: 0.8037 - loss: 0.5389 - val_accuracy: 0.6673 - val_auc: 0.8145 - val_loss: 0.5247
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6706 - auc: 0.8135 - loss: 0.5270 - val_accuracy: 0.6668 - val_auc: 0.8187 - val_loss: 0.5199
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6775 - auc: 0.8192 - loss: 0.5198 - val_accuracy: 0.6696 - val_auc: 0.8239 - val_loss: 0.5018
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6855 - auc: 0.8226 - loss: 0.5161 - val_accuracy: 0.7045 - val_auc: 0.8275 - val_loss: 0.4893
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6900 - auc: 0.8260 - loss: 0.5125 - val_accuracy: 0.6898 - val_auc: 0.8273 - val_loss: 0.5071
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6939 - auc: 0.8296 - loss: 0.5078 - val_accuracy: 0.6517 - val_auc: 0.8297 - val_loss: 0.5601
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6962 - auc: 0.8322 - loss: 0.5036 - val_accuracy: 0.7137 - val_auc: 0.8296 - val_loss: 0.4635
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6999 - auc: 0.8341 - loss: 0.5018 - val_accuracy: 0.6896 - val_auc: 0.8294 - val_loss: 0.4944
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7014 - auc: 0.8350 - loss: 0.5001 - val_accuracy: 0.7087 - val_auc: 0.8303 - val_loss: 0.4970
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6988 - auc: 0.8371 - loss: 0.4975 - val_accuracy: 0.7017 - val_auc: 0.8271 - val_loss: 0.4623
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7029 - auc: 0.8382 - loss: 0.4960 - val_accuracy: 0.6988 - val_auc: 0.8309 - val_loss: 0.5312
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7053 - auc: 0.8395 - loss: 0.4944 - val_accuracy: 0.7287 - val_auc: 0.8305 - val_loss: 0.4657
Epoch 14/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7038 - auc: 0.8409 - loss: 0.4919 - val_accuracy: 0.7181 - val_auc: 0.8329 - val_loss: 0.4788
Epoch 15/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7032 - auc: 0.8420 - loss: 0.4903 - val_accuracy: 0.6863 - val_auc: 0.8337 - val_loss: 0.5066
Epoch 16/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7048 - auc: 0.8434 - loss: 0.4886 - val_accuracy: 0.7251 - val_auc: 0.8355 - val_loss: 0.4755
Epoch 17/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7139 - auc: 0.8451 - loss: 0.4861 - val_accuracy: 0.7296 - val_auc: 0.8350 - val_loss: 0.4659
Epoch 18/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7072 - auc: 0.8453 - loss: 0.4872 - val_accuracy: 0.7208 - val_auc: 0.8328 - val_loss: 0.4637
Epoch 19/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7013 - auc: 0.8464 - loss: 0.4847 - val_accuracy: 0.6771 - val_auc: 0.8319 - val_loss: 0.4746
  ✔ best val_auc: 0.8355

[4/8] {'learning_rate': 0.001, 'dropout_rate': 0.3, 'l2_reg': 0.0001, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.6311 - auc: 0.7544 - loss: 0.7567 - val_accuracy: 0.6726 - val_auc: 0.7989 - val_loss: 0.6284
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6644 - auc: 0.8020 - loss: 0.6279 - val_accuracy: 0.6842 - val_auc: 0.8152 - val_loss: 0.6008
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6806 - auc: 0.8123 - loss: 0.5761 - val_accuracy: 0.6930 - val_auc: 0.8189 - val_loss: 0.5438
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6811 - auc: 0.8176 - loss: 0.5527 - val_accuracy: 0.6664 - val_auc: 0.8202 - val_loss: 0.5470
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6882 - auc: 0.8209 - loss: 0.5423 - val_accuracy: 0.6892 - val_auc: 0.8230 - val_loss: 0.5507
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6912 - auc: 0.8217 - loss: 0.5394 - val_accuracy: 0.7405 - val_auc: 0.8233 - val_loss: 0.5040
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6980 - auc: 0.8235 - loss: 0.5357 - val_accuracy: 0.6638 - val_auc: 0.8262 - val_loss: 0.6000
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6959 - auc: 0.8250 - loss: 0.5335 - val_accuracy: 0.7000 - val_auc: 0.8271 - val_loss: 0.5626
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7006 - auc: 0.8261 - loss: 0.5325 - val_accuracy: 0.7222 - val_auc: 0.8274 - val_loss: 0.5206
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7010 - auc: 0.8265 - loss: 0.5310 - val_accuracy: 0.6728 - val_auc: 0.8273 - val_loss: 0.5622
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7001 - auc: 0.8272 - loss: 0.5306 - val_accuracy: 0.7200 - val_auc: 0.8288 - val_loss: 0.5282
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7039 - auc: 0.8288 - loss: 0.5291 - val_accuracy: 0.7309 - val_auc: 0.8262 - val_loss: 0.4877
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6994 - auc: 0.8292 - loss: 0.5272 - val_accuracy: 0.7262 - val_auc: 0.8291 - val_loss: 0.4986
Epoch 14/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7055 - auc: 0.8297 - loss: 0.5273 - val_accuracy: 0.6981 - val_auc: 0.8308 - val_loss: 0.5417
Epoch 15/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7051 - auc: 0.8301 - loss: 0.5262 - val_accuracy: 0.7003 - val_auc: 0.8322 - val_loss: 0.5353
Epoch 16/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7029 - auc: 0.8304 - loss: 0.5260 - val_accuracy: 0.6611 - val_auc: 0.8294 - val_loss: 0.5736
Epoch 17/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7026 - auc: 0.8315 - loss: 0.5254 - val_accuracy: 0.7116 - val_auc: 0.8314 - val_loss: 0.5547
Epoch 18/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7062 - auc: 0.8328 - loss: 0.5233 - val_accuracy: 0.6805 - val_auc: 0.8292 - val_loss: 0.5541
  ✔ best val_auc: 0.8322

[5/8] {'learning_rate': 0.0005, 'dropout_rate': 0.1, 'l2_reg': 1e-06, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 19s 15ms/step - accuracy: 0.6495 - auc: 0.7739 - loss: 0.5696 - val_accuracy: 0.6812 - val_auc: 0.8055 - val_loss: 0.5121
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6842 - auc: 0.8149 - loss: 0.5226 - val_accuracy: 0.6552 - val_auc: 0.8167 - val_loss: 0.5600
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6935 - auc: 0.8263 - loss: 0.5086 - val_accuracy: 0.7231 - val_auc: 0.8235 - val_loss: 0.4987
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.6963 - auc: 0.8321 - loss: 0.5000 - val_accuracy: 0.7266 - val_auc: 0.8225 - val_loss: 0.5048
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7072 - auc: 0.8387 - loss: 0.4910 - val_accuracy: 0.7104 - val_auc: 0.8263 - val_loss: 0.5068
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 15ms/step - accuracy: 0.7084 - auc: 0.8431 - loss: 0.4850 - val_accuracy: 0.6762 - val_auc: 0.8273 - val_loss: 0.5336
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7112 - auc: 0.8484 - loss: 0.4769 - val_accuracy: 0.7368 - val_auc: 0.8269 - val_loss: 0.4653
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7153 - auc: 0.8519 - loss: 0.4712 - val_accuracy: 0.7315 - val_auc: 0.8280 - val_loss: 0.4670
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7209 - auc: 0.8565 - loss: 0.4640 - val_accuracy: 0.7099 - val_auc: 0.8286 - val_loss: 0.4890
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7268 - auc: 0.8602 - loss: 0.4582 - val_accuracy: 0.6923 - val_auc: 0.8309 - val_loss: 0.5079
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7288 - auc: 0.8652 - loss: 0.4496 - val_accuracy: 0.7453 - val_auc: 0.8259 - val_loss: 0.4730
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7321 - auc: 0.8690 - loss: 0.4437 - val_accuracy: 0.7275 - val_auc: 0.8290 - val_loss: 0.4933
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7355 - auc: 0.8734 - loss: 0.4349 - val_accuracy: 0.7349 - val_auc: 0.8265 - val_loss: 0.4605
  ✔ best val_auc: 0.8309

[6/8] {'learning_rate': 0.0005, 'dropout_rate': 0.1, 'l2_reg': 0.0001, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.6495 - auc: 0.7760 - loss: 0.7292 - val_accuracy: 0.6693 - val_auc: 0.8097 - val_loss: 0.6663
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.6830 - auc: 0.8155 - loss: 0.6165 - val_accuracy: 0.6953 - val_auc: 0.8156 - val_loss: 0.5876
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.6922 - auc: 0.8247 - loss: 0.5658 - val_accuracy: 0.6450 - val_auc: 0.8211 - val_loss: 0.6224
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.6976 - auc: 0.8315 - loss: 0.5361 - val_accuracy: 0.7107 - val_auc: 0.8254 - val_loss: 0.5468
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7038 - auc: 0.8351 - loss: 0.5214 - val_accuracy: 0.7012 - val_auc: 0.8276 - val_loss: 0.5380
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.7086 - auc: 0.8392 - loss: 0.5109 - val_accuracy: 0.6873 - val_auc: 0.8269 - val_loss: 0.5550
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7083 - auc: 0.8417 - loss: 0.5048 - val_accuracy: 0.7029 - val_auc: 0.8307 - val_loss: 0.5281
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7148 - auc: 0.8460 - loss: 0.4982 - val_accuracy: 0.6697 - val_auc: 0.8296 - val_loss: 0.5951
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7153 - auc: 0.8474 - loss: 0.4953 - val_accuracy: 0.7147 - val_auc: 0.8300 - val_loss: 0.5080
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.7159 - auc: 0.8495 - loss: 0.4916 - val_accuracy: 0.7310 - val_auc: 0.8302 - val_loss: 0.4906
  ✔ best val_auc: 0.8307

[7/8] {'learning_rate': 0.0005, 'dropout_rate': 0.3, 'l2_reg': 1e-06, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.6150 - auc: 0.7350 - loss: 0.6075 - val_accuracy: 0.6725 - val_auc: 0.7956 - val_loss: 0.5346
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.6602 - auc: 0.7954 - loss: 0.5474 - val_accuracy: 0.7141 - val_auc: 0.8088 - val_loss: 0.4936
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 0.6743 - auc: 0.8097 - loss: 0.5300 - val_accuracy: 0.6704 - val_auc: 0.8176 - val_loss: 0.5248
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 16s 14ms/step - accuracy: 0.6784 - auc: 0.8173 - loss: 0.5204 - val_accuracy: 0.6746 - val_auc: 0.8205 - val_loss: 0.5583
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6889 - auc: 0.8238 - loss: 0.5128 - val_accuracy: 0.6810 - val_auc: 0.8272 - val_loss: 0.5044
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6904 - auc: 0.8275 - loss: 0.5077 - val_accuracy: 0.7179 - val_auc: 0.8275 - val_loss: 0.4723
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6939 - auc: 0.8310 - loss: 0.5027 - val_accuracy: 0.7121 - val_auc: 0.8289 - val_loss: 0.5046
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7006 - auc: 0.8338 - loss: 0.4995 - val_accuracy: 0.7282 - val_auc: 0.8295 - val_loss: 0.4526
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7028 - auc: 0.8357 - loss: 0.4968 - val_accuracy: 0.6914 - val_auc: 0.8313 - val_loss: 0.5134
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7072 - auc: 0.8382 - loss: 0.4929 - val_accuracy: 0.7175 - val_auc: 0.8334 - val_loss: 0.4656
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7086 - auc: 0.8402 - loss: 0.4906 - val_accuracy: 0.7255 - val_auc: 0.8316 - val_loss: 0.4789
Epoch 12/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7101 - auc: 0.8419 - loss: 0.4876 - val_accuracy: 0.6999 - val_auc: 0.8316 - val_loss: 0.5093
Epoch 13/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7092 - auc: 0.8445 - loss: 0.4842 - val_accuracy: 0.7315 - val_auc: 0.8304 - val_loss: 0.4796
  ✔ best val_auc: 0.8334

[8/8] {'learning_rate': 0.0005, 'dropout_rate': 0.3, 'l2_reg': 0.0001, 'batch_size': 256, 'epochs': 200, 'hidden_units': 512}
Epoch 1/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 20s 15ms/step - accuracy: 0.6188 - auc: 0.7399 - loss: 0.7891 - val_accuracy: 0.6650 - val_auc: 0.8002 - val_loss: 0.6845
Epoch 2/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6565 - auc: 0.7956 - loss: 0.6844 - val_accuracy: 0.6456 - val_auc: 0.8124 - val_loss: 0.6714
Epoch 3/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6719 - auc: 0.8102 - loss: 0.6237 - val_accuracy: 0.6598 - val_auc: 0.8138 - val_loss: 0.6147
Epoch 4/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6841 - auc: 0.8178 - loss: 0.5827 - val_accuracy: 0.6985 - val_auc: 0.8244 - val_loss: 0.5462
Epoch 5/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6886 - auc: 0.8221 - loss: 0.5567 - val_accuracy: 0.7159 - val_auc: 0.8246 - val_loss: 0.5108
Epoch 6/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6931 - auc: 0.8256 - loss: 0.5413 - val_accuracy: 0.6780 - val_auc: 0.8264 - val_loss: 0.5564
Epoch 7/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6953 - auc: 0.8292 - loss: 0.5306 - val_accuracy: 0.6672 - val_auc: 0.8286 - val_loss: 0.5642
Epoch 8/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6992 - auc: 0.8308 - loss: 0.5258 - val_accuracy: 0.6778 - val_auc: 0.8296 - val_loss: 0.5671
Epoch 9/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6997 - auc: 0.8322 - loss: 0.5216 - val_accuracy: 0.6881 - val_auc: 0.8283 - val_loss: 0.5607
Epoch 10/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.6997 - auc: 0.8340 - loss: 0.5185 - val_accuracy: 0.7130 - val_auc: 0.8327 - val_loss: 0.5064
Epoch 11/200
1110/1110 ━━━━━━━━━━━━━━━━━━━━ 17s 15ms/step - accuracy: 0.7064 - auc: 0.8351 - loss: 0.5161 - val_accuracy: 0.6738 - val_auc: 0.8297 - val_loss: 0.5701
Epoch 12/200

## 3. Predictions

Generate predictions on the holdout test set using the best neural network model.

In [12]:
from features import get_test_data

selected_features = data.x_train.columns.tolist()
df_test = get_test_data("../data/bank_data_test.csv", data)
test_features = df_test[selected_features]

# Pick the model with the higher test AUC
best_nn_model = keras_best_model if keras_auc >= tf_auc else tf_best_model
print(
    f"Using {'Keras' if keras_auc >= tf_auc else 'TensorFlow'} model (AUC: {max(keras_auc, tf_auc):.4f})"
)

predictions = best_nn_model.predict(test_features, verbose=0)
predictions[:5]

Using TensorFlow model (AUC: 0.8355)

array([[0.6659443 ],
       [0.6310384 ],
       [0.07139289],
       [0.22145869],
       [0.00778314]], dtype=float32)

In [13]:
output_df = pd.DataFrame({
    'ID':     df_test['ID'],
    'TARGET': predictions.flatten(),
})
os.makedirs("../predictions", exist_ok=True)
output_df.to_csv("../predictions/churn_keras_predictions.csv", index=False)
print(f"Saved {len(output_df)} predictions to ../predictions/churn_keras_predictions.csv")
output_df.head()

Saved 88798 predictions to ../predictions/churn_keras_predictions.csv

       ID    TARGET
0  400980  0.665944
1  525062  0.631038
2  280316  0.071393
3  496066  0.221459
4  375031  0.007783

## 4. Results Summary

Comparison of all models: library, algorithm, key hyperparameters, accuracy and AUC.

In [15]:
results_table = pd.DataFrame(
    [
        {
            "Algorithm": "Naive Classifier (Most Frequent)",
            "Accuracy": round(naive_acc, 4),
            "AUC": round(naive_auc, 4),
            "Library": "scikit-learn",
            "Hyperparameters": "strategy=most_frequent",
        },
        {
            "Algorithm": "Random Forest",
            "Accuracy": round(rf_acc, 4),
            "AUC": round(rf_auc, 4),
            "Library": "scikit-learn",
            "Hyperparameters": (
                f"n_estimators={rf_best_params['n_estimators']}, "
                f"max_depth={rf_best_params['max_depth']}, "
                f"min_samples_split={rf_best_params['min_samples_split']}, "
                f"min_samples_leaf={rf_best_params['min_samples_leaf']}"
            ),
        },
        {
            "Algorithm": "MLPClassifier",
            "Accuracy": round(mlp_acc, 4),
            "AUC": round(mlp_auc, 4),
            "Library": "scikit-learn",
            "Hyperparameters": (
                f"hidden_layers={MLP_HIDDEN}, " f"lr={MLP_LR}, max_iter={MLP_MAX_ITER}"
            ),
        },
        {
            "Algorithm": "Neural Network",
            "Accuracy": round(keras_acc, 4),
            "AUC": round(keras_auc, 4),
            "Library": "Keras (TensorFlow)",
            "Hyperparameters": (
                f"lr={keras_params['learning_rate']}, "
                f"dropout={keras_params['dropout_rate']}, "
                f"l2={keras_params['l2_reg']}, "
                f"batch={keras_params['batch_size']}, "
                f"epochs={keras_params['epochs']}, "
                f"units={keras_params['hidden_units']}"
            ),
        },
        {
            "Algorithm": "Neural Network",
            "Accuracy": round(tf_acc, 4),
            "AUC": round(tf_auc, 4),
            "Library": "TensorFlow",
            "Hyperparameters": (
                f"lr={tf_params['learning_rate']}, "
                f"dropout={tf_params['dropout_rate']}, "
                f"l2={tf_params['l2_reg']}, "
                f"batch={tf_params['batch_size']}, "
                f"epochs={tf_params['epochs']}, "
                f"units={tf_params['hidden_units']}"
            ),
        },
        {
            "Algorithm": "Neural Network",
            "Accuracy": round(numpy_acc, 4),
            "AUC": round(numpy_auc, 4),
            "Library": "NumPy (custom)",
            "Hyperparameters": (
                f"hidden_layers={NUMPY_HIDDEN}, "
                f"lr={NUMPY_LR}, "
                f"epochs={NUMPY_EPOCHS}, "
                f"batch={NUMPY_BATCH}"
            ),
        },
    ]
)

results_table.index += 1
# display all columns and full cell content without truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
results_table

,Algorithm,Accuracy,AUC,Library,Hyperparameters
1,Naive Classifier (Most Frequent),0.9186,0.5000,scikit-learn,strategy=most_frequent
2,Random Forest,0.9194,0.8353,scikit-learn,"n_estimators=200, max_depth=20, min_samples_split=2, min_samples_leaf=2"
3,MLPClassifier,0.9174,0.8294,scikit-learn,"hidden_layers=(512, 256, 128), lr=0.001, max_iter=10"
4,Neural Network,0.7117,0.8321,Keras (TensorFlow),"lr=0.001, dropout=0.1, l2=1e-06, batch=256, epochs=200, units=512"
5,Neural Network,0.7251,0.8355,TensorFlow,"lr=0.0005, dropout=0.3, l2=0.0001, batch=256, epochs=200, units=512"
6,Neural Network,0.7045,0.8056,NumPy (custom),"hidden_layers=[512, 256, 128], lr=0.001, epochs=60, batch=256"